#! /bin/sh

sxhkd &
picom --experimental-backends --backend glx &
# picom -f &
nitrogen --restore &
nm-applet &
pasystray &
ulauncher &
~/bin/keyboard_layout.sh

# bspc monitor -d I II III IV V VI VII VIII IX X
if xrandr -q | grep 'HDMI1 connected'; then
    xrandr --output HDMI1 --mode 1920x1080 --right-of eDP1
    bspc monitor eDP1 -d I IV V VII X
    bspc monitor HDMI1 -d II III VI VIII IX
else
    bspc monitor eDP1 -d I II III IV V VI VII VIII
fi
xrandr --output eDP1 --mode 1920x1080

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a nautilus desktop='III' state=floating follow=on
bspc rule -a Gimp desktop='VIII' state=floating follow=on
bspc rule -a Chromium desktop='II'
bspc rule -a firefox desktop='II' follow=on
bspc rule -a Brave-browser desktop='II' follow=on
bspc rule -a discord desktop='V'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
